### ISSUE TITLE
Query breakage starting with 3.5.0 (returns unknown error)

### ISSUE THREAD

**Issue by DFoxinator** [neo4j/neo4j#12099]
Hi,

I'm testing out a query that was working on 3.4.10 on 3.5.0, and it causes a weird kind of cryptic error.

The high-level error that is returned/shows up in the Neo4j Browser when I run the query is: `Neo.DatabaseError.General.UnknownError: key not found: SymbolUse(r@105)`

Stack trace from debug.log is:
```
ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: key not found: SymbolUse(r@105), reference 449f603e-f58f-470e-a5f4-8ca6096b3687. key not found: SymbolUse(r@105)
java.util.NoSuchElementException: key not found: SymbolUse(r@105)
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at org.opencypher.v9_0.frontend.phases.Namespacer$$anonfun$variableRenamings$1.applyOrElse(Namespacer.scala:89)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
	at org.opencypher.v9_0.util.Foldable$.org$opencypher$v9_0$util$Foldable$$treeFoldAcc(Foldable.scala:165)
	at org.opencypher.v9_0.util.Foldable$FoldableAny$.treeFold$extension(Foldable.scala:83)
	at org.opencypher.v9_0.frontend.phases.Namespacer$.variableRenamings(Namespacer.scala:87)
	at org.opencypher.v9_0.frontend.phases.Namespacer$.process(Namespacer.scala:44)
	at org.opencypher.v9_0.frontend.phases.Namespacer$.process(Namespacer.scala:33)
	at org.opencypher.v9_0.frontend.phases.Phase$$anonfun$transform$1.apply(Phase.scala:35)
	at org.opencypher.v9_0.frontend.helpers.package$$anonfun$closing$1.apply(package.scala:23)
	at org.opencypher.v9_0.frontend.helpers.package$$anonfun$closing$1.apply(package.scala:23)
	at org.opencypher.v9_0.frontend.helpers.package$.using(package.scala:31)
	at org.opencypher.v9_0.frontend.helpers.package$.closing(package.scala:23)
	at org.opencypher.v9_0.frontend.phases.Phase$class.transform(Phase.scala:34)
	at org.opencypher.v9_0.frontend.phases.Namespacer$.transform(Namespacer.scala:33)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:63)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:59)
	at org.opencypher.v9_0.frontend.phases.If.transform(Transformer.scala:88)
	at org.opencypher.v9_0.frontend.phases.PipeLine.transform(Transformer.scala:63)
	at org.neo4j.cypher.internal.compiler.v3_5.CypherPlanner.planPreparedQuery(CypherPlanner.scala:57)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1.org$neo4j$cypher$internal$compatibility$v3_5$Cypher35Planner$$anonfun$$createPlan$1(Cypher35Planner.scala:151)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1$$anonfun$6.apply(Cypher35Planner.scala:169)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1$$anonfun$6.apply(Cypher35Planner.scala:169)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:167)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:126)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1.apply(Cypher35Planner.scala:167)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner$$anonfun$parseAndPlan$1.apply(Cypher35Planner.scala:116)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.v3_5.Cypher35Planner.parseAndPlan(Cypher35Planner.scala:116)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:82)
	at org.neo4j.cypher.internal.MasterCompiler.innerCompile$1(MasterCompiler.scala:115)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:150)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$compilers$3.apply(ExecutionEngine.scala:136)
	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$compilers$3.apply(ExecutionEngine.scala:136)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:167)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:126)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:156)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:95)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:189)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:506)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:300)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
	at org.neo4j.bolt.v3.runtime.ReadyState.processRunMessage(ReadyState.java:85)
	at org.neo4j.bolt.v3.runtime.ReadyState.processUnsafe(ReadyState.java:56)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:68)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:86)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

And the query is:
```
MATCH (me:User{id:123456}) 
WITH me 
MATCH (me)-[r:FOLLOWS]->(someone:User) 
WITH someone, me 
ORDER BY r.created_on DESC 
LIMIT 20 
WITH me, someone 
MATCH (someone)-[:FOLLOWS]->(someone_else:User)<-[:FOLLOWS]-(me) 
WITH someone, COUNT(someone_else) as n, me 
ORDER BY n DESC LIMIT 50 
MATCH (someone)-[r:FOLLOWS]->(someone_else:User) 
WITH someone_else, COUNT(someone_else) as n, me 
ORDER BY n DESC 
WITH someone_else, n, me 
WHERE NOT((me)-[:FOLLOWS]->(someone_else)) 
WITH someone_else, n 
RETURN someone_else, n  
ORDER BY n DESC  
LIMIT 20
```

Please let me know if you have any questions/need any additional info.

**Comment by InverseFalcon** [comment]
Hi, looks like the problem is with lines 4 and 5, ordering using a variable which isn't present in the preceding WITH clause. By changing your WITH to:

```
WITH someone, me, r
```
I'm seeing the problem go away.

As you said we had no issues with this kind of thing in 3.4.x, we'll investigate.

**Comment by DFoxinator** [comment]
@InverseFalcon thanks for the info, good find. I'll definitely change it to that for the 3.5.0 testing I'm doing. 

From my understanding of Cypher (I might be wrong) is that either WITH or RETURN should be able to include items in the ORDER BY that are not in the WITH or RETURN list, so I'm thinking maybe the 3.4.x behavior is the correct one.

**Comment by Hunterness** [comment]
Hi, we have confirmed the error and will look into it and get back to you.

**Comment by nosoccomtothom** [comment]
Hi there,
Same issue here. Was working fine until upgraded to 3.5.0. Was working fine on 3.2.6

```
profile 
                WITH timestamp() as ts,'(?i)Name' as almost_name
                    OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
                    WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
                    return *
```

Drops

`Neo.DatabaseError.General.UnknownError: Unknown variable `ts`.`

Adding `CYPHER 3.1` runs as before but fails when setting 3.4 or 3.5

**Comment by Lojjs** [comment]
@nosoccomtothom I'm not able to reproduce your error on an empty 3.5.0 graph. Have you written the query exactly like you posted it here? Do you have any indexes?

**Comment by Lojjs** [comment]
@DFoxinator Your error was due to a bug in our semantic checking. A fix  has been merged and will be included in the 3.5.1 release.

**Comment by DFoxinator** [comment]
Thanks @Lojjs!

**Comment by nosoccomtothom** [comment]
Thanks @Lojjs !!
Sorry for the late reply. The query was not running on 3.5.0 nor 3.4 therefore had to enforce 3.1. Indeed the query uses indexes.

**Comment by Lojjs** [comment]
@nosoccomtothom 3.5.1 will come shortly. When it is out, can you test again with that version? If it still doesn't work, please open a separate Github issue with as much info that you have about your setup (patch release, indexes and if possible a sample database).

Best regards Louise

**Comment by nosoccomtothom** [comment]
@Lojjs Certainly will do. Thanks for the hard work!!

**Comment by mikesname** [comment]
Hi - another example here of a (contrived) query which runs on 3.4 but fails on 3.5.1:

    MATCH (n1:Label1)-[:TEST]-(n2:Label2) 
    OPTIONAL MATCH (n2)-[:TEST2]-(n3) 
    WHERE n3 IS NULL OR n3 <> n1 
    RETURN n1.prop1, n2.prop2;

On 3.5.1 this fails with `key not found: Variable(n3)`.

If you remove the `OR n3 <> n1` part of the `WHERE` clause it runs okay. There are no indexes that exist for the labels/props here on the databases I'm testing on.

**Comment by Lojjs** [comment]
@mikesname Thanks for your feedback. As far as I can see, that seems to be a separate bug, appearing both in 3.4 and 3.5. If it works in 3.4 for you, I guess the Cypher planner chooses another plan for your db than for my simple example database. However, I've made a fix for it, so from 3.4.12 and 3.5.2 it should be working again.

**Comment by mikesname** [comment]
@Lojjs My apologies, I should indeed have put 3.3 as the working version - thanks for the fix!

**Comment by InverseFalcon** [comment]
@mikesname Just letting you know, even with a bug fix this isn't quite a correct query. The null check should not be part of the WHERE clause here, since the WHERE clause is part of the preceding OPTIONAL MATCH. Instead, since the intent is to filter just to rows where n3 is null or something different than n1, a WITH clause should be used instead (so the WHERE clause is now paired with the WITH instead of the OPTIONAL MATCH):

```
MATCH (n1:Label1)-[:TEST]-(n2:Label2) 
OPTIONAL MATCH (n2)-[:TEST2]-(n3) 
WITH n1, n2, n3
WHERE n3 IS NULL OR n3 <> n1 
RETURN n1.prop1, n2.prop2;
```

See our [knowledge base article on using the WHERE clause](https://neo4j.com/developer/kb/why-where-clause-does-not-filter/) for more explanation and examples of WHERE clause behavior when paired with an OPTIONAL MATCH.

**Comment by nosoccomtothom** [comment]
Hi @Lojjs 
Upgraded to 3.5.1 but the error still continues. Created the #12128 as suggested.
