### ISSUE TITLE
neo4j-import fails on "Prepare node index phase" (java.lang.StackOverflowError)

### ISSUE THREAD

**Issue by 0xNacho** [neo4j/neo4j#4935]
Hi There,

I'm trying to import 130M~ nodes and 200M~ relationships using the **neo4-import** tool.

The problem is that neo4j-import gets stuck on the process (after more than 1'30'').

The output of the process:

```
Nodes [>:3.35 MB/s---|PROPERTIES(2)======|*NODE:1007.08 MB------|LABEL SCAN-----|v:7.46 MB/s(2)======]131M
Done in 1h 35m 47s 332ms
Prepare node index
[*SORT:1.47 GB---------------------------------------------------------------------------------] 87M
```

And the messages.log content is:

```
2015-06-15 10:38:56.423+0000 INFO  [org.neo4j]: Import starting
2015-06-15 10:38:56.537+0000 INFO  [org.neo4j]: Creating new db @ /var/user/neo/graph22.db/neostore
2015-06-15 10:38:57.264+0000 INFO  [org.neo4j]: Missing counts store, rebuilding it.
2015-06-15 10:38:57.536+0000 INFO  [org.neo4j]: No lucene scan store index found, this might just be first use. Preparing to rebuild.
2015-06-15 10:38:57.581+0000 INFO  [org.neo4j]: No lucene scan store index found, this might just be first use. Preparing to rebuild.
2015-06-15 10:38:57.793+0000 INFO  [org.neo4j]: Rebuilding lucene scan store, this may take a while
2015-06-15 10:38:57.796+0000 INFO  [org.neo4j]: Lucene scan store rebuilt (roughly -1 nodes)
2015-06-15 18:29:33.509+0000 INFO  [org.neo4j]: About to rotate counts store at transaction 1 to [/var/user/neo/graph22.db/neostore.counts.db.b], from [/var/user/neo/graph22.db/neostore.counts.db.a].
2015-06-15 18:29:33.516+0000 INFO  [org.neo4j]: Successfully rotated counts store at transaction 1 to [/var/user/neo/graph22.db/neostore.counts.db.b], from [/var/user/neo/graph22.db/neostore.counts.db.a].
2015-06-15 18:29:33.771+0000 ERROR [org.neo4j]: Error during import null
java.lang.StackOverflowError
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.partition(ParallelSort.java:193)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:243)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
```

It sounds like a recursion bug. What can I do?

Im using **neo4j-community-2.2.2** version.

Thanks in advance.

**Comment by cleishm** [comment]
Likely resolved by #4094 (included in Neo4j 2.2.3). Please verify issues with the latest patch releases when opening issues.

**Comment by 0xNacho** [comment]
I already tried it with **neo4j-community-2.2.3**, but keeps failing.

**Comment by 0xNacho** [comment]
When  [neo4j-community-2.2.3](http://neo4j.com/artifact.php?name=neo4j-community-2.2.3-unix.tar.gz)  was updated?

**Comment by cleishm** [comment]
Hi @0xNacho,

Neo4j 2.2.3 was released on June 23.

If you're still seeing the issue with Neo4j 2.2.3, it may be that the previous fix was insufficient. Please post the error from 2.2.3, along with as much detail as needed to reproduce the problem, and I'll be happy to reopen the issue.

Cheers,
Chris

**Comment by 0xNacho** [comment]
Hi @cleishm, 

Thanks for the reply.

I cannot provide more details since I'm dealing with sensitive data.

The only thing I know is that  the program always gets stuck at the same point (89M~).

Could it  be a bug that always is reproduced after X iterations? We are processing 20 types of nodes and 30 types of relationships. Please find below the node & relationships files list:

| Node Files | Number of Lines |
| --- | --- |
| File 1 | 63561 |
| File 2 | 682956 |
| File 3 | 5703198 |
| File 4 | 544 |
| File 5 | 15474695 |
| File 6 | 446061 |
| File 7 | 2709 |
| File 8 | 3246 |
| File 9 | 2724760 |
| File 10 | 1282900 |
| File 11 | 21169952 |
| File 12 | 2257 |
| File 13 | 2684459 |
| File 14 | 29379898 |
| File 15 | 23008542 |
| File 16 | 142514 |
| File 17 | 19387132 |
| File 18 | 5080142 |
| File 19 | 5293 |
| File 20 | 6972817 |

| Relationship Files | Number of Lines |
| --- | --- |
| File 1 | 182468 |
| File 2 | 223903 |
| File 3 | 23011748 |
| File 4 | 6952437 |
| File 5 | 4872539 |
| File 6 | 6206793 |
| File 7 | 23010756 |
| File 8 | 22894504 |
| File 9 | 12670624 |
| File 10 | 12219949 |
| File 11 | 13499687 |
| File 12 | 4526585 |
| File 13 | 16672228 |
| File 14 | 1856246 |
| File 15 | 530208 |
| File 16 | 3246 |
| File 17 | 4366292 |
| File 18 | 3195 |
| File 19 | 2724760 |
| File 20 | 1527909 |
| File 21 | 24209131 |
| File 22 | 2762 |
| File 23 | 2684459 |
| File 24 | 2605140 |
| File 25 | 2209743 |
| File 26 | 19387132 |
| File 27 | 10822013 |
| File 28 | 2684459 |
| File 29 | 2818308 |
| File 30 | 5017503 |

**Comment by jexp** [comment]
Hi,

thanks for reporting this.
Could you perhaps share just the headers and some fake data to get an idea about the structure?
And also your command-line invocation.

Do you by chance know if your id's are already sorted in some way?
If you can you could experiment with --id-type integer vs --id-type string

**Comment by 0xNacho** [comment]
Hi.

First of all, I apologize for getting back to you late.

We've just discovered a header file like this:

```
 header1$header2$$header4 
```

We fixed the header and now everything works fine, so we suppose this file was causing the bug.

**Comment by cdraxler** [comment]
Hi,

I too have encountered a stack overflow problem upon importing from a large (?) csv file. I installed neo4j community edition 2.2.3 yesterday and it's running on a MacBook 17 with Yosemite and 8GB RAM. I restarted the machine prior to running neo4j-install.

Here's what I did:

bin/neo4j-import --into data/graph.db --nodes /Users/draxler/Sites/Sprachdatenbanken/SpeechDatabases/neo4j/MAU_Ziffern.csv --nodes /Users/draxler/Sites/Sprachdatenbanken/SpeechDatabases/neo4j/ORT_Ziffern.csv 
Unable to find any JVMs matching version "1.7".
Importing the contents of these files into data/graph.db:
Nodes:
  /Users/draxler/Sites/Sprachdatenbanken/SpeechDatabases/neo4j/MAU_Ziffern.csv

  /Users/draxler/Sites/Sprachdatenbanken/SpeechDatabases/neo4j/ORT_Ziffern.csv

Available memory:
  Free machine memory: 3,88 GB
  Max heap memory : 1,78 GB

Nodes
[_>:4,28 MB/s-----------------|PROPERTIES(3|NODE:7,63 MB---|LABEL SCAN-------------|v:8,32 MB/s]980k
Done in 11s 184ms
Prepare node index
[_SORT:11,35 MB--------------------------------------------------------------------------------]210kException in thread "SortWorker-0" java.lang.StackOverflowError
    at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:245)
    at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
    at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
    at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)

Every few hundred error messages there's a new thread name

```
at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
```

Exception in thread "Thread-3" java.lang.StackOverflowError
    at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:245)

Here's a look at the files (Mau and Ort are the node names, Mau contains roughly 780K lines, Ort 211 K lines.

--- Ort data ---
id:ID,position,label,signalfile_id,reference,:LABEL
17051340,0,zwo,16921280,21991594,Ort
17067534,0,acht,16921281,21991595,Ort
21681506,0,vier,16921282,21991596,Ort
21376391,0,fünf,16921283,21991597,Ort

--- Mau data ---
position,label,begin,duration,signalfile_id,reference,:LABEL
0,t,16096,17859,16921280,17051340,Mau
1,s,33956,1984,16921280,17051340,Mau
2,v,35941,2645,16921280,17051340,Mau
3,o,38587,5070,16921280,17051340,Mau
0,?,31531,881,16921281,17067534,Mau
1,a,32413,1763,16921281,17067534,Mau
2,x,34177,3527,16921281,17067534,Mau
3,t,37705,12788,16921281,17067534,Mau

**Comment by cdraxler** [comment]
I tried again, with an ID as the first column of the Mau data. No change, same error.

Christoph

**Comment by 0xNacho** [comment]
Hi @cdraxler 
Can you check that all the rows have the same number of fields?

**Comment by cdraxler** [comment]
Hi,

I imported the Mau-table back into PostgreSQL and it imported the file without reporting incomplete lines. Shall I put the files into Dropbox?

Best, Christoph

**Comment by 0xNacho** [comment]
@cdraxler yes.
I'm sure it will be useful for the neo4j guys. (Consider using [Gist](https://gist.github.com/) instead of Dropbox)

**Comment by cdraxler** [comment]
Hi,

here's the link to the file on Dropbox:

https://www.dropbox.com/s/a7x3mfedb4kahbh/MAU_Ziffern_2.csv?dl=0

Christoph

**Comment by tinwelint** [comment]
This has been fixed by https://github.com/neo4j/neo4j/pull/4877 where an iterative/stack on heap is used instead of execution stack for quick-sort. This will prevent these StackOverflowErrors. Next release of 2.2.x and eventually 2.3 will include this fix.

**Comment by mchutani** [comment]
I ran into the same problem while using ~9MB file for import.


Available memory:
  Free machine memory: 1.19 GB
  Max heap memory : 1.71 GB

Nodes
[>:13.25 M|PROPE|NODE:7.|*LABEL SCAN----------------------------------|v:5.44 MB/s-------------]100k


It fails after this with the following error:
Exception in thread "main" java.lang.StackOverflowError
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.partition(ParallelSort.java:193)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:243)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)


I am using 2.2.3 version.
Any updates for the fix?

**Comment by mayankchutani** [comment]
I ran into the same problem while using ~9MB file for import. Available memory: Free machine memory: 1.19 GB Max heap memory : 1.71 GB Nodes [>:13.25 M|PROPE|NODE:7.|*LABEL SCAN----------------------------------|v:5.44 MB/s-------------]100k It fails after this with the following error: Exception in thread "main" java.lang.StackOverflowError at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.partition(ParallelSort.java:193) at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:243) at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246) at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246) at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246) at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246) at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246) I am using 2.2.3 version. Any updates for the fix?

**Comment by mayankchutani** [comment]
I ran into the same problem while using ~9MB file for import.

Available memory:
  Free machine memory: 843.44 MB
  Max heap memory : 1.71 GB

Nodes
[>:7.0|PR|NODE|*LABEL SCAN----------------------------------------|v:1.15 MB/s-----------------] 30k

After 30-40 seconds, I get the following error:
Exception in thread "main" java.lang.StackOverflowError
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.partition(ParallelSort.java:193)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:243)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)
        at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.ParallelSort.recursiveQsort(ParallelSort.java:246)

I am using 2.2.3 version. Any updates for the fix?

**Comment by 0xNacho** [comment]
I really think the problem is not fixed yet, despite of the @tinwelint comment

**Comment by mchutani** [comment]
Yes it hasn't.
May be the 2.2.4 release would have something fixed on this, as he mentioned.

**Comment by jexp** [comment]
@mchutani could you share your import file(s) with me personally (michael at neo4j.com) so that I could try it with a snapshot build for 2.2.4 ?

**Comment by mayankchutani** [comment]
@jexp The data is confidential, but I can share it with dummy data.
I will email you in sometime. Thanks for responding.

**Comment by tinwelint** [comment]
@mayankchutani that method `recursiveQsort` doesn't exist in 2.2.4 so if there's still a problem, it's another one. But please try the same import on 2.2.4.

**Comment by mayankchutani** [comment]
@tinwelint @jexp neo4j-import works just fine in 2.2.4. The import is so damn fast. Loving it. 
I think you can close this issue now.

**Comment by jexp** [comment]
Yes :) Importing stackoverflow into neo4j:

```
IMPORT DONE in 3m 48s 579ms. Imported:
  31138559 nodes
  77930024 relationships
  260665346 properties
```

**Comment by mayankchutani** [comment]
Mine was:

`````` language
    IMPORT DONE in 5s 727ms. Imported:
      147387 nodes
      147380 relationships
      1031533 properties```
``````

**Comment by tinwelint** [comment]
Lovely!

**Comment by tinylion1024** [comment]
There is something wrong with your file format. Please check it.
